services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=plusdb