ALTER TABLE HOSPITAL_ADMISSION
ADD COLUMN consultation BIGINT;

ALTER TABLE HOSPITAL_ADMISSION
ADD CONSTRAINT fk_consultation_admission
FOREIGN KEY(consultation)
REFERENCES CONSULTATION(ID)
ON DELETE CASCADE;