ALTER TABLE PATIENT
ADD COLUMN register_Moment TIMESTAMP;

ALTER TABLE HEALTH_PROFESSIONAL
ADD COLUMN document VARCHAR(11) UNIQUE;

ALTER TABLE HEALTH_PROFESSIONAL
ADD COLUMN register_Moment TIMESTAMP;


