ALTER TABLE HOSPITAL_ADMISSION
ADD COLUMN daily_Cost DECIMAL(10,2);

ALTER TABLE HOSPITAL_ADMISSION
ADD COLUMN total_Cost DECIMAL(100,2);

ALTER TABLE HEALTH_PROFESSIONAL
ADD COLUMN signature VARCHAR(100);