CREATE TABLE HEALTH_PROFESSIONAL(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE ,
    phone VARCHAR(11) ,
    password VARCHAR(150) NOT NULL,
    profession VARCHAR(50) NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    role VARCHAR(13) NOT NULL
)