ALTER TABLE CONSULTATION
ADD COLUMN professional BIGINT;

ALTER TABLE CONSULTATION
ADD CONSTRAINT fk_professional_consult
FOREIGN KEY (professional)
REFERENCES HEALTH_PROFESSIONAL(id)
ON DELETE CASCADE;