CREATE TABLE PRESCRIPTION(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(350) NOT NULL,
    prescription_Date TIMESTAMP NOT NUll,
    type VARCHAR(9) NOT NULL,
    signature VARCHAR(100) NOT NULL
)