ALTER TABLE MEDICAL_EXAMINATION
ADD COLUMN consultation BIGINT;

ALTER TABLE MEDICAL_EXAMINATION
ADD CONSTRAINT fk_consultation_exam
FOREIGN KEY (consultation)
REFERENCES CONSULTATION(id)
ON DELETE CASCADE;